project:
  type: website
  output-dir: docs

website:
  title: "Alice MacQueen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



